// <auto-generated />
using System;
using EmployeesCRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeesCRUD.Migrations
{
    [DbContext(typeof(EmployeesProjectsDBContext))]
    [Migration("20200901095642_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeesCRUD.Tables.EmployeesTable", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("HourlyWage")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeesTable");
                });

            modelBuilder.Entity("EmployeesCRUD.Tables.JobOrdersTable", b =>
                {
                    b.Property<int>("JobOrdersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("JobOrdersId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("JobOrdersTable");
                });

            modelBuilder.Entity("EmployeesCRUD.Tables.ProjectEmployeesTable", b =>
                {
                    b.Property<int>("ProjectEmployeesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeesTableEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectsTableProjectId")
                        .HasColumnType("int");

                    b.HasKey("ProjectEmployeesId");

                    b.HasIndex("EmployeesTableEmployeeId");

                    b.HasIndex("ProjectsTableProjectId");

                    b.ToTable("ProjectEmployeesTable");
                });

            modelBuilder.Entity("EmployeesCRUD.Tables.ProjectsTable", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectsTable");
                });

            modelBuilder.Entity("EmployeesCRUD.Tables.JobOrdersTable", b =>
                {
                    b.HasOne("EmployeesCRUD.Tables.EmployeesTable", "Employee")
                        .WithMany("JobOrder")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeesCRUD.Tables.ProjectsTable", "Project")
                        .WithMany("JobOrder")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeesCRUD.Tables.ProjectEmployeesTable", b =>
                {
                    b.HasOne("EmployeesCRUD.Tables.EmployeesTable", null)
                        .WithMany("ProjectEmployee")
                        .HasForeignKey("EmployeesTableEmployeeId");

                    b.HasOne("EmployeesCRUD.Tables.ProjectsTable", null)
                        .WithMany("ProjectEmployee")
                        .HasForeignKey("ProjectsTableProjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
